### ISSUE TITLE
ProcessOutCoreUI is using `Generate Asset Symbols` and it does not compile with Tuist or Bazel

### ISSUE THREAD

**Issue by albsala-backmarket** [processout/processout-ios#317]
Hi there! We're migrating our project to [Tuist](https://tuist.io) and `ProcessOutCoreUI` fails when compiling. I believe it's related with (at least) `ProcessOutCoreUI` using Xcode's `Generate Asset Symbols` feature. This feature seems to work when working with Xcode+SwiftPM, but not in other contexts, such as [Tuist](https://tuist.io), [Bazel](https://bazel.build), and probably other tools.
Solution would be stop using this feature and including the necessary code.

I'm attaching some simple example.
[TuistExample.zip](https://github.com/user-attachments/files/16414125/TuistExample.zip)

**Comment by albsala-backmarket** [comment]
We carried out some investigation about this and it turns out _Xcode's Generate Asset Symbols_ only seems to work for apps and dynamic frameworks. Tuist and Bazel seem to use static ones by default so they will fail unless you convert these targets to dynamic. This also affects flexibility as projects can't play with dynamic and static on debug/release.
We might be wrong, so please feel free to share your findings. But my suggestion would be avoid using this feature.
Thank you

**Comment by andrii-vysotskyi-cko** [comment]
Hi!

Carried out my own investigation that also confirms your findings. It works only for dynamic frameworks because underneath Tuist is generating separate resource bundle (along with custom bundle [accessor](https://docs.tuist.io/guides/develop/projects/synthesized-files#bundle-accessors)) for statically linked dependencies. So there are no resources to generate symbols for hence compilation error.

Also didn't find another workaround except changing product type for all PO products to `.framework` so most probably we will drop Xcode's generated symbols.

As for timeline as far as I understand it is not critical since workaround exists but will try to deliver it this week. Hope it works

**Comment by albsala-backmarket** [comment]
Thank you @andrii-vysotskyi-cko ! 

I think this is more an Xcode issue rather than Tuist or Bazel ones, since this _Generate Asset Symbols_ is an Xcode feature that seems to work only for apps and dynamic frameworks, as I found out during the investigation.

Tuist, as you mentioned, also generates bundle and assets accessors using SwiftGen, regardless of the target type. We don't use it at the moment though.

We'll continue using dynamic frameworks for ProcessOut, so it's not a blocker for us at the moment, but we'll appreciate if you let us know when it can be used with static ones.

Thank you again!

**Comment by andrii-vysotskyi-cko** [comment]
Hi @albsala-backmarket, should be resolved in `4.19.0`

**Comment by albsala-backmarket** [comment]
I'm sorry I didn't confirmed the fix, but it worked. Thank you!
